#!/usr/local/bin/perl

use Compress::Zlib ;

binmode STDIN;
binmode STDOUT;
$x = deflateInit()
   or die "Cannot create a deflation stream\n" ;

while (<>)
{
    ($output, $status) = $x->deflate($_) ;

    $status == Z_OK
        or die "deflation failed\n" ;

    print $output ;
}

($output, $status) = $x->flush() ;

$status == Z_OK
    or die "deflation failed\n" ;

print $output ;
